//
//  Constants.h
//  zeepointIOS
//
//  Created by Carlos Bayona on 4/15/15.
//  Copyright (c) 2015 zeepoint. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constants : NSObject

FOUNDATION_EXPORT NSString *const IP;

FOUNDATION_EXPORT NSString *const WS;

FOUNDATION_EXPORT NSString *const WS_ENVIROMENT;

FOUNDATION_EXPORT NSString *const CREATE_ZPOINT_SERVICE;

FOUNDATION_EXPORT NSString *const GET_ZPOINTS_SERVICE;

FOUNDATION_EXPORT NSString *const GET_FAV_ZPOINTS_SERVICE;

FOUNDATION_EXPORT NSString *const SAVE_USER_INFO;

FOUNDATION_EXPORT NSString *const LOGIN_USER_SERVICE;

FOUNDATION_EXPORT NSString *const JOIN_ZPOINT_SERVICE;

FOUNDATION_EXPORT NSString *const EXIT_ZPOINT_SERVICE;

FOUNDATION_EXPORT NSString *const FB_USER_PIC;

FOUNDATION_EXPORT NSString *const GET_PREVIOUS_MSGS;

FOUNDATION_EXPORT NSString *const GET_USERS_SERVICE;

FOUNDATION_EXPORT NSString *const CLOUDINARY_SERVICE;

FOUNDATION_EXPORT NSString *const TEXT_MESSAGE;

FOUNDATION_EXPORT NSString *const PHOTO_MESSAGE;

FOUNDATION_EXPORT NSString *const STOMP_DESTINATION;

@end
